import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fcf9f0",
        "surface-bright": "#fcf9f0",
        "surface-dim": "#dddad1",
        "surface-variant": "#e5e2da",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ea",
        "surface-container": "#f1eee5",
        "surface-container-high": "#ebe8df",
        "surface-container-highest": "#e5e2da",
        "surface-tint": "#825500",
        "on-surface": "#1c1c17",
        "on-surface-variant": "#40484a",
        "inverse-surface": "#31312b",
        "inverse-on-surface": "#f4f1e8",
        background: "#fcf9f0",
        "on-background": "#1c1c17",
        primary: "#412800",
        "primary-container": "#5f3d00",
        "primary-fixed": "#ffddb4",
        "primary-fixed-dim": "#ffb953",
        "on-primary": "#ffffff",
        "on-primary-container": "#eba22d",
        "on-primary-fixed": "#291800",
        "on-primary-fixed-variant": "#633f00",
        "inverse-primary": "#ffb953",
        secondary: "#2a6673",
        "secondary-container": "#afe9f8",
        "secondary-fixed": "#b2ecfa",
        "secondary-fixed-dim": "#96d0de",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#2f6a77",
        "on-secondary-fixed": "#001f25",
        "on-secondary-fixed-variant": "#064e5a",
        tertiary: "#4d2100",
        "tertiary-container": "#6f3300",
        "tertiary-fixed": "#ffdbc8",
        "tertiary-fixed-dim": "#ffb689",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff9750",
        "on-tertiary-fixed": "#321300",
        "on-tertiary-fixed-variant": "#743500",
        outline: "#70787b",
        "outline-variant": "#bfc8ca",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        petrol: "#004B57",
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
      animation: { float: "float 3s ease-in-out infinite" },
    },
  },
  plugins: [forms],
} satisfies Config;
